/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
 //   <div className="flex gap-3 items-start cursor-pointer border-2 border-indigo-600 rounded p-2 w-full my-auto" onClick={onClick}> for the side view
const FeatureItem = ({ icon, title, description, onClick }) => (
  <div className="flex gap-3 items-start cursor-pointer border-2 hover:border-indigo-600 rounded p-2 w-full my-auto mt-3" onClick={onClick}>
    {icon ? <img
      loading="lazy"
      src={icon}
      className="object-contain shrink-0 aspect-square w-[45px]"
      alt=""
    /> :<p></p>}
    <div className="flex-auto mt-1.5 max-md:max-w-full">
      <h3 className="text-2xl font-extrabold text-purple-950">{title}</h3>
      {description && (
        <p className="mt-3 text-xl font-medium text-zinc-500 max-md:max-w-full">
          {description}
        </p>
      )}
    </div>
  </div>
);

const FeatureSideItem = ({  title, description }) => (
  <div className="self-center flex gap-3 items-start p-2 w-full my-auto " >
    
    <div className="flex-auto mt-1.5 max-md:max-w-full">
      <h3 className="text-2xl font-extrabold text-purple-950">{title}</h3>
      {description && (
        <p className="mt-3 text-xl font-medium text-zinc-500 max-md:max-w-full">
          {description}
        </p>
      )}
    </div>
  </div>
);

const FeatureSection = () => {
  const features = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8ed5aabbc38e7641f89aead3f83c778251b4aea3a937d4dceaaaa76e40028aa7?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0",
      title: "Advanced Legals & Esign",
      description:"A secure platform for managing legal documents and contracts, allowing buyers and sellers to digitally sign agreements. Ensures compliance with Indian regulations, streamlining the transaction process.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b1efadcacb46653382413f416a1edb16449927d105146d7abf9bdd4189d78be8?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0",
      title: "Dynamic Message Environment",
      description:"A real-time messaging system that enables seamless communication between buyers and sellers. Facilitates quick negotiations, updates, and discussions directly within the platform.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/9f265e37224c66baea210c3db84c0b859f0c2fd5f93ffb3ce558110e9adf2d71?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0",
      title: "Accurate & Secured Information",
      description:"Provides verified and reliable data, ensuring that all listings and user details are trustworthy. Protects sensitive information with advanced security measures to maintain privacy and integrity.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/21d6a28466b3a35b00db7f77f14fccbdf57474f1628cd91646c9e11b67f0ffb2?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0",
      title: "Buyer & Seller Insurance",
      description:"Offers protection for both buyers and sellers, covering potential risks during transactions. Ensures a secure environment by safeguarding against financial losses or disputes.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/416d1bdf260cf1ff810c2ee12d77e491aee6f2e1b6744347664a6102e6abe9d9?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0",
      title: "Outstanding Comparison Insights",
      description:"Enables users to compare multiple listings with detailed insights, helping them make informed decisions. Highlights key differences and similarities, ensuring the best value selection.",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c1a613da8401aa99b27043d3eebe1b92719aa60366a677ae81437b7e49f96ed3?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0",
      title: "Secured Payments",
      description:"Facilitates safe and encrypted transactions, ensuring that payments are protected from fraud. Offers peace of mind by securely handling funds throughout the transaction process.",
    },
  ];

  const [item,setItem]=useState(0);

  return (
    <section className="flex flex-col px-12 pt-10 pb-36 w-full bg-white bg-opacity-90 max-md:px-5 max-md:pb-24 max-md:max-w-full">
      <h2 className="self-center text-3xl font-extrabold text-center text-neutral-700 max-md:max-w-full">
        Mango is an organized and secured all-in-one platform dedicated
        exclusively to help you buy and sell global digital assets.
      </h2>
      <div className="self-center mt-12 -mb-7 w-full max-w-[1103px] max-md:mt-10 max-md:mb-2.5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col items-start w-full text-2xl font-extrabold text-purple-950 max-md:mt-10 max-md:max-w-full">
              {features.map((feature, index) => (
                <FeatureItem
                  key={index}
                  onClick={()=> setItem(index)}
                  icon={feature.icon}
                  title={feature.title}
                />
              ))}
            </div>
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <FeatureSideItem
              // icon="https://cdn.builder.io/api/v1/image/assets/TEMP/8ed5aabbc38e7641f89aead3f83c778251b4aea3a937d4dceaaaa76e40028aa7?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0"
              title={features[item].title}
              description={features[item].description}/>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FeatureSection;
