/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Link } from "react-router-dom";

const Header = () => {
  return (
    <div className=" sticky top-0">
    <header className=" flex flex-wrap gap-2 justify-between items-start px-5 pt-3 pb-3 w-full bg-indigo-950 max-md:px-5 max-md:max-w-full">
      <h1 className="text-4xl text-white">mango.</h1>
      <div className="flex gap-10 ">
        <div className="flex gap-5">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/498441aa3f0bd02e4cb1f60f5578c51872110291291322cd70c7f4514dadeda9?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0"
            className="object-contain shrink-0 aspect-square w-[35px]"
            alt=""
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a76400f58b6172712ddab769a27ab1ac7a9f176618e504895a6434167fea185c?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0"
            className="object-contain shrink-0 aspect-square w-[35px]"
            alt=""
          />
        </div>
        <div className="flex gap-0.5 text-base font-extrabold text-purple-950">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f585995714b82554733eeb7f7602594eb0186b093fd8036e1b0eb16d69235820?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0"
            className="object-contain shrink-0 aspect-square w-[35px]"
            alt=""
          />
          <Link to="/signup" className="px-3.5 py-2 bg-white rounded-[100px]">
            Sign up
          </Link>
        </div>
      </div>
    </header>
     <nav className=" flex flex-wrap gap-5 justify-between px-5 py-2 w-full text-xl font-extrabold bg-white max-md:px-5 max-md:max-w-full border-2">
     <div className="flex flex-wrap gap-10 self-start text-purple-950">
       <div className="grow my-auto">Explore</div>
       {/* <div className="flex flex-auto gap-6"> */}
         <Link className="my-auto">Insights</Link>
         <div className="my-auto">Content</div>
         <div className="my-auto">Pricing</div>
         <Link
           to="/earn"
           className="pt-2.5 pb-3 hover:text-white hover:bg-purple-950 hover:px-4 hover:rounded-[50px] max-md:px-5"
         >
           Earn with us
         </Link>
       {/* </div> */}
     </div>
     <div className="flex gap-2">
       <Link
         to="/contact"
         className="px-4 pt-2.5 pb-3 bg-white border-2 hover:text-white hover:bg-purple-950 border-solid border-purple-950 rounded-[100px] text-purple-950 max-md:px-5"
       >
         Contact us
       </Link>
       <Link
         to="/sell"
         className="self-start px-4 pt-2.5 pb-3 text-white bg-purple-950 rounded-[100px] max-md:px-5"
       >
         Sell Now
       </Link>
     </div>
   </nav>
   </div>

  );
};

export default Header;
