/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Hero = () => {
  return (
    <section className="flex flex-col items-center bg-custom-purple px-20 pt-20 pb-72 w-full text-center  min-h-[752px] max-md:px-5 max-md:pb-24 max-md:max-w-full">
      {/* <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/6c049dd14aba4942b3aa7cf3186a847797dc1ede5343619382701e032e449db0?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0"
        className="object-cover absolute inset-0 size-full"
        alt="Background image"
      /> */}
      <div className="flex flex-col mb-0 w-full max-w-[900px] max-md:mb-2.5 max-md:max-w-full">
        <h2 className="self-center text-5xl font-extrabold text-white w-[632px] max-md:max-w-full max-md:text-4xl">
          #1 Marketplace to Buy & Sell Digital Assets in India.
        </h2>
        <form className="flex flex-row gap-2 p-1.5 lg:mt-28 text-2xl font-semibold bg-white rounded-[100px] max-md:mt-10">
          <div className="self-center flex gap-1 px-2 py-2 text-white bg-purple-950 rounded-[100px] max-md:px-3">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/498441aa3f0bd02e4cb1f60f5578c51872110291291322cd70c7f4514dadeda9?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0"
              className="object-contain shrink-0 self-start aspect-square w-[35px]"
              alt=""
            />
            <button type="submit">Search</button>
          </div>
          <input
            type="text"
            placeholder="e.g. Amazon Stoers"
            className="flex-auto my-auto text-purple-300 w-[644px] rounded-[100px] max-md:max-w-full"
            aria-label="Search for digital assets"
          />
        </form>
        <div className="flex flex-wrap gap-3.5 items-start self-start mt-9 text-sm font-bold text-white whitespace-nowrap">
          <div className="grow pt-1 self-stretch text-xl font-extrabold">
            Popular:
          </div>
          {["SaaS", "Shopify", "Amazon", "Blog", "Youtube"].map(
            (tag, index) => (
              <div
                key={index}
                className="my-auto px-5 pt-2.5 pb-2.5 border border-white border-solid rounded-[100px]"
              >
                {tag}
              </div>
            )
          )}
        </div>
      </div>
    </section>
  );
};

export default Hero;
