/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Navigation from "./Navigation";
import Hero from "./Hero";
import FeatureSection from "./FeatureSection";
import ListingsSection from "./ListingsSection";

const Layout = () => {
  return (
    <div className="flex overflow-hidden flex-col">
     
      <main>
        <Hero />
        <div className="flex w-full bg-white bg-opacity-90 min-h-[133px] max-md:max-w-full" />
        <FeatureSection />
        <ListingsSection />
      </main>
    </div>
  );
};

export default Layout;
