/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ListingCard from "./ListingCard";

const ListingsSection = () => {
  const listings = [
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ef6f52397239a4c24a3f3d004d52215c15c79f86191b6da03f7f9c14a7e4f446?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0",
      title: "hightailtransport.com",
      country: "United States",
      description:
        "A truck dispatching service and a SaaS transportation management system (TMS) that helps trucking carriers and dispatchers streamline their businesses.",
      tags: ["SaaS", "Travel", "Services"],
      siteAge: "<1year",
      netProfit: "NA/p/m",
      price: "USD $5,950",
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/67def6a54a134d4eef0d7209a56abb2048f22d721cb15ce126e2c3f5ca4e6b65?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0",
      title: "Kitchen Dropship Store Ready to Earn",
      country: "United States",
      description:
        "Password: 1,Kitchen Dropshipping Store For Active & Passive Income | Proven Profitable Niche | Fast Shipping | Ready To Earn For Entrepreneur| Shopify",
      tags: ["Ecommerce", "Home", "Dropshipping"],
      siteAge: "<1year",
      netProfit: "NA/p/m",
      price: "USD $200",
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/e5a59b28c5b3dcc5b80a7f7aa4a359dda9d5ee1e29bcc89615f816b8d4084bd5?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0",
      title: "Plug Paralegal",
      country: "United States",
      description:
        "The first nationwide b2c paralegal and legal document preparation company of its kind. This company provides swift legal services to customers all over the U.S.",
      tags: ["Service", "Business", "Services"],
      siteAge: "<1year",
      netProfit: "USD $5,500 p/m",
      price: "USD $73,180",
    },
  ];

  return (
    <section className="flex z-10 flex-col px-12 pt-28 pb-56 mt-0 w-full bg-white max-md:px-5 max-md:py-24 max-md:max-w-full">
      <h2 className="self-start text-3xl font-extrabold text-neutral-700 max-md:max-w-full">
        Explore suggested listings for you
      </h2>
      {listings.map((listing, index) => (
        <ListingCard key={index} {...listing} />
      ))}
      <button className="self-center mt-11 mb-0 text-xl font-extrabold text-purple-950 max-md:mt-10 max-md:mb-2.5">
        See more
      </button>
    </section>
  );
};

export default ListingsSection;
