/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ListingCard = ({
  image,
  title,
  country,
  description,
  tags,
  siteAge,
  netProfit,
  price,
}) => {
  return (
    <div className="px-7 py-7 mt-7 w-full rounded-md border border-solid bg-white bg-opacity-80 border-zinc-300 max-md:px-5 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-[81%] max-md:ml-0 max-md:w-full">
          <div className="max-md:mt-10 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col">
              <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                <img
                  loading="lazy"
                  src={image}
                  className="object-contain grow w-full rounded-md aspect-[1.2] shadow-[0px_4px_4px_rgba(0,0,0,0.4)] max-md:mt-10"
                  alt={title}
                />
              </div>
              <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                <div className="flex flex-col items-start w-full text-base max-md:mt-10">
                  <h3 className="text-2xl font-extrabold text-purple-950">
                    {title}
                  </h3>
                  <div className="flex mt-2 text-xs font-extrabold text-zinc-500">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/4ebfb6ec21d2345cef1735595ff48e695833d82f7c017d627bf8206b21342a59?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0"
                      className="bg-cover bg-center bg-no-repeat object-contain shrink-0 w-4 aspect-square "
                      alt=""
                    />
                    <div>{country}</div>
                  </div>
                  <p className="self-stretch mt-2 font-medium text-neutral-700">
                    {description}
                  </p>
                  <div className="flex gap-3 mt-2 font-medium whitespace-nowrap text-zinc-500">
                    {tags.map((tag, index) => (
                      <div
                        key={index}
                        className="my-auto px-6 pt-2.5 pb-3 border border-solid border-zinc-300 rounded-[100px]"
                      >
                        {tag}
                      </div>
                    ))}
                  </div>
                  <div className="flex gap-5 mt-8">
                    <div className="flex flex-col">
                      <div className="font-medium text-zinc-500">Site Age</div>
                      <div className="self-start font-bold text-black">
                        {siteAge}
                      </div>
                    </div>
                    <div className="shrink-0 self-start w-px border border-black border-solid h-[21px]" />
                    <div className="flex flex-col">
                      <div className="font-medium text-zinc-500">
                        Net Profit
                      </div>
                      <div className="self-start font-bold text-black">
                        {netProfit}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[19%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col mt-2.5 w-full max-md:mt-10">
            <div className="flex flex-col items-end pr-px pl-9 max-md:pl-5">
              <div className="text-xs font-medium text-zinc-500">
                Bidding Price
              </div>
              <div className="text-xl font-extrabold text-black">{price}</div>
            </div>
            <div className="flex gap-2 mt-52 max-md:mt-10">
              <button className="px-3 pt-2.5 pb-2.5 text-base flex items-center  font-bold whitespace-nowrap border-2 border-solid border-purple-950 rounded-[100px] text-purple-950">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/edb17847e8650744d2d674383ab3a5083f727fcfc8c3acc29a11e3a804b925b0?placeholderIfAbsent=true&apiKey=42bb954c825745999302100cb42c8fd0"
                  className="pt-0.5 mx-auto my-auto  shrink-0 self-start w-5 aspect-square"
                  alt=""
                />
                <span>View</span>
              </button>
              <button className="px-3 pt-2.5 pb-3 text-xs font-extrabold text-white border-2 border-solid bg-purple-950 border-purple-950 rounded-[100px]">
                See Listing
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ListingCard;
