/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Link } from "react-router-dom";

const Navigation = () => {
  return (
    <nav className=" sticky top-0 flex flex-wrap gap-5 justify-between px-7 py-6 w-full text-xl font-extrabold bg-white max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-10 self-start text-purple-950">
        <div className="grow my-auto">Explore</div>
        {/* <div className="flex flex-auto gap-6"> */}
          <div className="my-auto">Insights</div>
          <div className="my-auto">Content</div>
          <div className="my-auto">Pricing</div>
          <Link
            to="/earn"
            className="px-6 pt-2.5 pb-3 text-white bg-purple-950 rounded-[100px] max-md:px-5"
          >
            Earn with us
          </Link>
        {/* </div> */}
      </div>
      <div className="flex gap-2">
        <Link
          to="/contact"
          className="px-6 pt-2.5 pb-3 bg-white border-2 border-solid border-purple-950 rounded-[100px] text-purple-950 max-md:px-5"
        >
          Contact us
        </Link>
        <Link
          to="/sell"
          className="self-start px-6 pt-2.5 pb-3 text-white bg-purple-950 rounded-[100px] max-md:px-5"
        >
          Sell Now
        </Link>
      </div>
    </nav>
  );
};

export default Navigation;
